#!/bin/bash
source $ZSHREP/themes/cmd-display.sh
action=$1

available_commands=(
  unban
  ban
  list
  ignore
  ignorelist
  alert
)

valid_cmd=false
for cmd in "${available_commands[@]}"; do
  if [[ "$action" == "$cmd" ]]; then
    valid_cmd=true
    break
  fi
done

if ! $valid_cmd; then
echo "$(basename $0): incorrect action.
usage: $(basename $0) ban/ignore ip (time)
usage: $(basename $0) unban ip
usage: $(basename $0) list/ignorelist/alert
"
fi

zsh_cmd=(sudo cscli)

jail=le_whitelist
target=$2
time=$3
case $action in
  ban) zsh_cmd+=(decisions add --ip) ;;
  unban) zsh_cmd+=(decisions delete --ip) ;;
  list) zsh_cmd+=(decisions list) ;;
  alert) zsh_cmd+=(alerts list) ;;
  ignore) zsh_cmd+=(allowlists add $jail) ;;
  ignorelist) zsh_cmd+=(allowlists inspect $jail) ;;
esac

if [[ -n "$target" && "$target" =~ $ip_address ]]; then
  zsh_cmd+=($target)
  [[ -n "$time" ]] && {
    [[ "$action" == "ban" ]] && zsh_cmd+=(--duration $time)
    [[ "$action" == "ignore" ]] && zsh_cmd+=(--expiration $time)
  }
elif [[ -n "$target" && ! ( "$target" =~ $ip_address ) ]]; then
  echo "$(basename $0): incorrect ip input"
elif [[ "$action" == *--ip && -z "$target" ]]; then
  echo "$(basename $0): ban/unban requires ip"
fi
zsheval "${zsh_cmd[@]}"
