#!/bin/bash
source $ZSHREP/themes/cmd-display.sh
action=$1

[[ "$action" != "unban" && "$action" != "ban" ]] && {
echo "$(basename $0): incorrect action.
usage: $(basename $0) ban/unban jail ip"
}

jail=$2
zsh_cmd=(sudo fail2ban-client set $jail)
[[ "$action" == "ban" ]] && action=banip
[[ "$action" == "unban" ]] && action=unbanip
zsh_cmd+=($action)

target=$3
if [[ -n "$target" && "$target" =~ $ip_address ]]; then
  zsh_cmd+=($target)
elif [[ -n "$target" && ! ( "$target" =~ $ip_address ) ]]; then
  echo "$(basename $0): incorrect ip input"
elif [[ "$action" == *element && "$jail" =~ $ip_address ]]; then
  echo "$(basename $0): ban/unban requires jail before ip"
elif [[ "$action" == *element && -z "$target" ]]; then
  echo "$(basename $0): ban/unban requires ip"
fi
zsheval "${zsh_cmd[@]}"
