#!/bin/bash
action=$1

available_commands=(
  unban
  ban
  list
  rules
)

valid_cmd=false
for cmd in "${available_commands[@]}"; do
  if [[ "$action" == "$cmd" ]]; then
    valid_cmd=true
    break
  fi
done

if ! $valid_cmd; then
echo "$(basename $0): incorrect action.
usage: $(basename $0) ban set ip (time)
usage: $(basename $0) unban set ip
usage: $(basename $0) list/rules
"
fi

zsh_cmd=(sudo nft)
case $action in
  ban) zsh_cmd+=(add element) ;;
  unban) zsh_cmd+=(delete element) ;;
  list) zsh_cmd+=(list set) ;;
  rules) zsh_cmd+=(list table) ;;
esac

jail=$2
target=$3
time=$4
zsh_cmd+=(inet filter $jail)

if [[ -n "$target" && "$target" =~ $ip_address ]]; then
  if [[ -n "$time" ]] && [[ "$jail" == "whitelist" || "$jail" == "blacklist" ]]; then
    zsh_cmd+=({ $target timeout $time })
  else
    zsh_cmd+=({ $target })
  fi
elif [[ -n "$target" && ! ( "$target" =~ $ip_address ) ]]; then
  echo "$(basename $0): incorrect ip input"
elif [[ "$action" == *element && "$jail" =~ $ip_address ]]; then
  echo "$(basename $0): ban/unban requires set before ip"
elif [[ "$action" == *element && -z "$target" ]]; then
  echo "$(basename $0): ban/unban requires ip"
fi

zsheval "${zsh_cmd[@]}"
