alias digs='dig +short'
alias listen='sudo ss -tulpn | grep'
alias sed-crlf="sed -i 's/\r$//'"
alias bat='batcat'
alias lah='ls -lah'
alias gitc='git -C'
alias gitls='git ls-files'
alias sudo='sudo '
alias diffs='diff -sy --color'
