#!/usr/bin/env zsh
source $ZSHREP/fzf/presets/main.sh

# listed in $ZSHREP/common/aliases.zsh
if [[ $# == 1 ]]; then

  git_commands=(
    add
    restore
  )
  for subcmd in "${git_commands[@]}"; do
    [[ "$1" == "$subcmd" ]] && gitsubcmd="$1"
  done
  shift

elif [[ $# == 2 ]]; then

  git_commands=(
    restore
    --staged
  )
  for subcmd in "${git_commands[@]}"; do
    for arg in "$@"; do
      [[ "$arg" == "$subcmd" ]] && gitsubcmd="$@"
    done
  done
  shift 2

else gitsubcmd="add"; fi

gitcmd=(git)

[[ -d "$1" ]] && gitcmd+=(-C "$1")
[[ -f "$1" ]] && gitcmd+=(-C "$(dirname $1)")
[[ -n "$1" ]] && repo_path="$("${gitcmd[@]}" rev-parse --show-toplevel)/"

gitignore="${repo_path}.gitignore"
[[ -f "$gitignore" ]] && gitignore_arg=(-X "$gitignore") || gitignore_arg=()

# preview_bat "${repo_path}{2}" git
preview_git diff "$repo_path" "${repo_path}{2}" "{1}"
bind_gitinfo "$repo_path" "${repo_path}{2}" "{1}"

execcmd=("${gitcmd[@]}")
execcmd+=("$gitsubcmd")
bind_exec "${(j: :)execcmd[@]}" "${repo_path}{+2}"

### --find-renames has no effect -_-
gitcmd+=(
  status
  --porcelain
  --find-renames
  "${gitignore_arg[@]}"
)

"${gitcmd[@]}" | \
fzf "${fzfdefaults[@]}" \
    "${previewcmd[@]}" \
    "${briefinfo[@]}" \
    "${bindexec[@]}" \
    --multi
